import { LinkOption } from './links-builder.model';

// Move this logic to backend.
export const linkOptions: LinkOption[] = [
  {
    id: 'github',
    name: 'GitHub',
    icon: 'pi pi-github',
    backgroundColor: '#333333',
    textColor: '#FFFFFF',
  },
  {
    id: 'twitter',
    name: 'Twitter',
    icon: 'pi pi-twitter',
    backgroundColor: '#1DA1F2',
    textColor: '#FFFFFF',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    icon: 'pi pi-linkedin',
    backgroundColor: '#0A66C2',
    textColor: '#FFFFFF',
  },
  {
    id: 'youtube',
    name: 'YouTube',
    icon: 'pi pi-youtube',
    backgroundColor: '#FF0000',
    textColor: '#FFFFFF',
  },
  {
    id: 'facebook',
    name: 'Facebook',
    icon: 'pi pi-facebook',
    backgroundColor: '#1877F2',
    textColor: '#FFFFFF',
  },
  {
    id: 'instagram',
    name: 'Instagram',
    icon: 'pi pi-instagram',
    backgroundColor: '#E4405F',
    textColor: '#FFFFFF',
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    icon: 'pi pi-tiktok',
    backgroundColor: '#000000',
    textColor: '#FFFFFF',
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    icon: 'pi pi-pinterest',
    backgroundColor: '#E60023',
    textColor: '#FFFFFF',
  },
  {
    id: 'twitch',
    name: 'Twitch',
    icon: 'pi pi-twitch',
    backgroundColor: '#9146FF',
    textColor: '#FFFFFF',
  },
  {
    id: 'stackoverflow',
    name: 'Stack Overflow',
    icon: 'pi pi-code',
    backgroundColor: '#F48024',
    textColor: '#FFFFFF',
  },
  {
    id: 'leetcode',
    name: 'LeetCode',
    icon: 'pi pi-code',
    backgroundColor: '#FFA116',
    textColor: '#000000',
  },
  {
    id: 'discord',
    name: 'Discord',
    icon: 'pi pi-discord',
    backgroundColor: '#5865F2',
    textColor: '#FFFFFF',
  },
  {
    id: 'reddit',
    name: 'Reddit',
    icon: 'pi pi-reddit',
    backgroundColor: '#FF4500',
    textColor: '#FFFFFF',
  },
  {
    id: 'medium',
    name: 'Medium',
    icon: 'pi pi-book',
    backgroundColor: '#000000',
    textColor: '#FFFFFF',
  },
  {
    id: 'behance',
    name: 'Behance',
    icon: 'pi pi-circle',
    backgroundColor: '#1769FF',
    textColor: '#FFFFFF',
  },
  {
    id: 'spotify',
    name: 'Spotify',
    icon: 'pi pi-headphones',
    backgroundColor: '#1DB954',
    textColor: '#FFFFFF',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    icon: 'pi pi-telegram',
    backgroundColor: '#0088CC',
    textColor: '#FFFFFF',
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    icon: 'pi pi-whatsapp',
    backgroundColor: '#25D366',
    textColor: '#FFFFFF',
  },
];
